import { Patient } from '../../shared/types';

/**
 * Initial patient data seeded from patient_data.csv
 * This is used to populate localStorage on first load
 */
export const SEED_PATIENTS: Patient[] = [
  {
    patientId: 'MRN8472',
    patientName: 'Maria Garcia',
    dob: '1958-03-15',
    gender: 'F',
    phone: '555-0101',
    email: 'mgarcia@email.com',
    preferredLanguage: 'Spanish',
    admissionDate: '2026-01-02',
    dischargeDate: '2026-01-10',
    dischargeTime: '14:30',
    lengthOfStay: 3,
    primaryDiagnosis: 'Heart failure exacerbation',
    dischargeDisposition: 'Home with home health',
    dischargeMedications: 'Furosemide 40mg daily, Carvedilol 25mg BID, Lisinopril 20mg daily',
    allergies: 'Penicillin',
    attendingPhysician: 'Dr. Robert Chen',
    pcpName: 'Dr. Susan Chen',
    pcpPhone: '555-2001',
    readmissionRiskScore: 'High',
    fallRisk: 'Low',
    notes: 'Lives alone - daughter visits weekly',
  },
  {
    patientId: 'MRN3391',
    patientName: 'James Wilson',
    dob: '1942-07-22',
    gender: 'M',
    phone: '555-0102',
    email: null,
    preferredLanguage: 'English',
    admissionDate: '2026-01-04',
    dischargeDate: '2026-01-11',
    dischargeTime: '10:15',
    lengthOfStay: 2,
    primaryDiagnosis: 'Hip replacement',
    dischargeDisposition: 'Home',
    dischargeMedications: 'Oxycodone 5mg q4h PRN, Enoxaparin 40mg daily x14d, Acetaminophen 1000mg q6h',
    allergies: 'NKDA',
    attendingPhysician: 'Dr. Patricia Moore',
    pcpName: null,
    pcpPhone: null,
    readmissionRiskScore: 'Low',
    fallRisk: 'High',
    notes: 'Daughter is primary caregiver',
  },
  {
    patientId: 'MRN5028',
    patientName: 'Sarah Chen',
    dob: '1979-11-08',
    gender: 'F',
    phone: null,
    email: 'schen@email.com',
    preferredLanguage: 'English',
    admissionDate: '2026-01-01',
    dischargeDate: '2026-01-09',
    dischargeTime: '16:45',
    lengthOfStay: 3,
    primaryDiagnosis: 'Pneumonia',
    dischargeDisposition: 'Home',
    dischargeMedications: 'Azithromycin 250mg daily x4d, Albuterol inhaler PRN',
    allergies: 'Sulfa drugs',
    attendingPhysician: 'Dr. Michael Torres',
    pcpName: 'Dr. Michael Rodriguez',
    pcpPhone: '555-2003',
    readmissionRiskScore: 'Medium',
    fallRisk: null,
    notes: 'Unreachable by phone - email preferred',
  },
  {
    patientId: 'MRN7745',
    patientName: 'Robert Taylor',
    dob: '1965-05-30',
    gender: 'M',
    phone: '555-0104',
    email: 'rtaylor@email.com',
    preferredLanguage: 'English',
    admissionDate: '2026-01-12',
    dischargeDate: '2026-01-06',
    dischargeTime: '09:00',
    lengthOfStay: 3,
    primaryDiagnosis: 'Diabetic foot infection',
    dischargeDisposition: 'Home with home health',
    dischargeMedications: 'Insulin glargine 30u qHS, Levofloxacin 750mg daily x10d, Metformin 1000mg BID',
    allergies: 'NKDA',
    attendingPhysician: 'Dr. Sarah Kim',
    pcpName: 'Dr. James Kumar',
    pcpPhone: '555-2004',
    readmissionRiskScore: 'High',
    fallRisk: 'Low',
    notes: 'Wound vac in place',
  },
  {
    patientId: 'MRN2156',
    patientName: 'Linda Martinez',
    dob: '1951-09-18',
    gender: 'F',
    phone: '555-0105',
    email: null,
    preferredLanguage: 'Spanish',
    admissionDate: '2026-01-02',
    dischargeDate: '2026-01-09',
    dischargeTime: null,
    lengthOfStay: 3,
    primaryDiagnosis: 'COPD exacerbation',
    dischargeDisposition: 'Home',
    dischargeMedications: 'Prednisone 40mg daily x5d taper, Albuterol MDI q4h, Advair 250/50 BID, Azithromycin 250mg daily x5d',
    allergies: null,
    attendingPhysician: 'Dr. Robert Chen',
    pcpName: 'Dr. Susan Chen',
    pcpPhone: '555-2001',
    readmissionRiskScore: 'High',
    fallRisk: 'Low',
    notes: 'Home oxygen 2L continuous',
  },
  {
    patientId: 'MRN9382',
    patientName: 'David Park',
    dob: '1968-02-25',
    gender: 'M',
    phone: '555-0106',
    email: 'dpark@email.com',
    preferredLanguage: 'Korean',
    admissionDate: '2025-12-31',
    dischargeDate: '2026-01-09',
    dischargeTime: '11:20',
    lengthOfStay: 3,
    primaryDiagnosis: 'Stroke',
    dischargeDisposition: 'Home with home health',
    dischargeMedications: 'Aspirin 325mg daily, Atorvastatin 80mg qHS, Plavix 75mg daily',
    allergies: 'NKDA',
    attendingPhysician: 'Dr. Jennifer Wu',
    pcpName: 'Dr. Patricia Lee',
    pcpPhone: '555-2005',
    readmissionRiskScore: 'Very High',
    fallRisk: 'High',
    notes: 'Left-sided weakness - wife is caregiver',
  },
  {
    patientId: 'MRN4419',
    patientName: 'Jennifer Brown',
    dob: '1955-12-03',
    gender: 'F',
    phone: '555-0107',
    email: null,
    preferredLanguage: 'English',
    admissionDate: '2026-01-03',
    dischargeDate: '2026-01-12',
    dischargeTime: '13:45',
    lengthOfStay: 3,
    primaryDiagnosis: 'Sepsis secondary to UTI',
    dischargeDisposition: 'Skilled nursing facility',
    dischargeMedications: 'Ceftriaxone IV daily x7d',
    allergies: 'Latex',
    attendingPhysician: 'Dr. Michael Torres',
    pcpName: null,
    pcpPhone: null,
    readmissionRiskScore: 'Medium',
    fallRisk: 'Medium',
    notes: 'Transferred to Sunrise SNF',
  },
  {
    patientId: 'MRN6633',
    patientName: 'Michael Thompson',
    dob: '1982-04-17',
    gender: 'M',
    phone: null,
    email: 'mthompson@email.com',
    preferredLanguage: 'English',
    admissionDate: '2026-01-03',
    dischargeDate: '2026-01-11',
    dischargeTime: '08:30',
    lengthOfStay: 1,
    primaryDiagnosis: 'Chest pain - ruled out MI',
    dischargeDisposition: 'Home',
    dischargeMedications: 'Continue home medications',
    allergies: 'NKDA',
    attendingPhysician: 'Dr. Sarah Kim',
    pcpName: 'Dr. Michael Rodriguez',
    pcpPhone: '555-2003',
    readmissionRiskScore: 'Low',
    fallRisk: null,
    notes: 'Stress test ordered - outpatient',
  },
  {
    patientId: 'MRN1847',
    patientName: 'Patricia Davis',
    dob: '1971-06-29',
    gender: 'F',
    phone: '555-0109',
    email: 'pdavis@email.com',
    preferredLanguage: 'English',
    admissionDate: '2026-01-02',
    dischargeDate: '2026-01-10',
    dischargeTime: '15:00',
    lengthOfStay: 3,
    primaryDiagnosis: 'GI bleed',
    dischargeDisposition: 'Home',
    dischargeMedications: 'Omeprazole 40mg BID, Sucralfate 1g QID',
    allergies: 'Codeine',
    attendingPhysician: 'Dr. Patricia Moore',
    pcpName: 'Dr. James Kumar',
    pcpPhone: null,
    readmissionRiskScore: 'Medium',
    fallRisk: 'Low',
    notes: null,
  },
  {
    patientId: 'MRN5591',
    patientName: 'William Lee',
    dob: '1949-11-11',
    gender: 'M',
    phone: null,
    email: null,
    preferredLanguage: 'Mandarin',
    admissionDate: '2026-01-03',
    dischargeDate: '2026-01-06',
    dischargeTime: null,
    lengthOfStay: 3,
    primaryDiagnosis: 'Acute kidney injury',
    dischargeDisposition: 'Home with home health',
    dischargeMedications: 'Discontinue lisinopril, reduce metformin to 500mg daily',
    allergies: 'NKDA',
    attendingPhysician: 'Dr. Jennifer Wu',
    pcpName: 'Dr. Susan Chen',
    pcpPhone: '555-2001',
    readmissionRiskScore: 'Medium',
    fallRisk: 'Low',
    notes: 'Difficult to reach - daughter traveling',
  },
  {
    patientId: 'MRN8264',
    patientName: 'Elizabeth Moore',
    dob: '1938-08-05',
    gender: 'F',
    phone: '555-0111',
    email: null,
    preferredLanguage: 'English',
    admissionDate: '2025-12-29',
    dischargeDate: '2026-01-13',
    dischargeTime: '10:45',
    lengthOfStay: 5,
    primaryDiagnosis: 'Hip fracture (nonoperative)',
    dischargeDisposition: 'Skilled nursing facility',
    dischargeMedications: 'Oxycodone 5mg q6h PRN, Calcium/Vit D, Alendronate 70mg weekly',
    allergies: 'Morphine',
    attendingPhysician: 'Dr. Robert Chen',
    pcpName: null,
    pcpPhone: null,
    readmissionRiskScore: 'Medium',
    fallRisk: 'Very High',
    notes: 'At Meadowbrook Rehab',
  },
  {
    patientId: 'MRN3975',
    patientName: 'Charles Anderson',
    dob: '1963-10-20',
    gender: 'M',
    phone: '555-0112',
    email: 'canderson@email.com',
    preferredLanguage: 'English',
    admissionDate: '2026-01-01',
    dischargeDate: '2026-01-12',
    dischargeTime: '14:00',
    lengthOfStay: 4,
    primaryDiagnosis: 'COVID-19 pneumonia',
    dischargeDisposition: 'Home',
    dischargeMedications: 'Dexamethasone 6mg daily x5d',
    allergies: 'NKDA',
    attendingPhysician: 'Dr. Michael Torres',
    pcpName: 'Dr. Patricia Lee',
    pcpPhone: '555-2005',
    readmissionRiskScore: 'Medium',
    fallRisk: 'Low',
    notes: 'Home isolation precautions',
  },
  {
    patientId: 'MRN7138',
    patientName: 'Margaret White',
    dob: '1956-03-28',
    gender: 'F',
    phone: '555-0113',
    email: null,
    preferredLanguage: 'English',
    admissionDate: '2026-01-03',
    dischargeDate: '2026-01-10',
    dischargeTime: '09:30',
    lengthOfStay: 3,
    primaryDiagnosis: 'Cellulitis',
    dischargeDisposition: 'Home',
    dischargeMedications: 'Ceftriaxone 2g IV daily x7d via home infusion',
    allergies: 'Penicillin',
    attendingPhysician: 'Dr. Sarah Kim',
    pcpName: null,
    pcpPhone: null,
    readmissionRiskScore: 'Low',
    fallRisk: 'Low',
    notes: 'Home infusion coordinating',
  },
  {
    patientId: 'MRN2803',
    patientName: 'Joseph Martinez',
    dob: '1975-07-14',
    gender: 'M',
    phone: null,
    email: null,
    preferredLanguage: 'Spanish',
    admissionDate: '2026-01-01',
    dischargeDate: '2026-01-09',
    dischargeTime: null,
    lengthOfStay: 3,
    primaryDiagnosis: 'Hypertensive emergency',
    dischargeDisposition: 'Home',
    dischargeMedications: 'Amlodipine 10mg daily, Lisinopril 40mg daily, Metoprolol 100mg BID, HCTZ 25mg daily',
    allergies: null,
    attendingPhysician: 'Dr. Patricia Moore',
    pcpName: 'Dr. Michael Rodriguez',
    pcpPhone: '555-2003',
    readmissionRiskScore: 'High',
    fallRisk: 'Low',
    notes: 'Medication non-adherence suspected',
  },
  {
    patientId: 'MRN9520',
    patientName: 'Barbara Harris',
    dob: '1944-01-09',
    gender: 'F',
    phone: '555-0115',
    email: 'bharris@email.com',
    preferredLanguage: 'English',
    admissionDate: '2026-01-03',
    dischargeDate: '2026-01-11',
    dischargeTime: '16:20',
    lengthOfStay: 2,
    primaryDiagnosis: 'Syncope',
    dischargeDisposition: 'Home',
    dischargeMedications: 'Continue home meds, hold metoprolol',
    allergies: 'Aspirin',
    attendingPhysician: 'Dr. Jennifer Wu',
    pcpName: 'Dr. James Kumar',
    pcpPhone: '555-2004',
    readmissionRiskScore: 'Medium',
    fallRisk: 'High',
    notes: 'Holter monitor placed',
  },
];
